### ISSUE TITLE
Implement Jaccard index?

### ISSUE THREAD

**Issue by luizirber** [Daniel-Liu-c0deb0t/triple_accel#2]
Hi @Daniel-Liu-c0deb0t!

I didn't dig down too much into the codebase, but I wonder if there is interest in adding a Jaccard index function (as described in [Faster Population Counts Using AVX2 Instructions](https://arxiv.org/abs/1611.07612).
The implementation from the paper is at https://github.com/CountOnes/hamming_weight/blob/1dd7554c0fc39e01c9d7fa54372fd4eccf458875/src/avx_jaccard_index.c
and while it is a bit heavy on the macros I think it could be translated using the infra you already have in triple_accel?

(This would be incredibly useful for me, so I can start looking deeper into it if you're also interested =])

**Comment by Daniel-Liu-c0deb0t** [comment]
Hey @luizirber, I think it would be a bit difficult to integrate Jaccard distance into the current codebase, since it is mainly adapted for the Levenshtein distance calculation. It would likely be easier to make a separate crate for Jaccard index. I considered this feature before, but I thought it would be better to only focus on edit distance. Additionally, I'm current too busy with other projects to implement it. Sorry. Eventually, I would likely implement SIMD popcount in Rust in a separate project, since I don't believe anyone has done it yet and its very useful. If you have time to look into it, then I think it shouldn't be too hard to get a Rust port, as the code is not too long. The dense macros are just to make it work on multiple platforms.

**Comment by luizirber** [comment]
No problem =]

**Comment by Daniel-Liu-c0deb0t** [comment]
Hey @luizirber, I am interested in implementing an SSE/AVX popcount routine in another project: https://github.com/natir/nuc2bit. Perhaps you can use the code (when I am done) to implement a Jaccard distance function?

**Comment by luizirber** [comment]
Sounds great, and happy to see you working with Pierre =]

**Comment by Daniel-Liu-c0deb0t** [comment]
Hey, I wrote up a quick popcount implementation [here](https://github.com/natir/nuc2bit/blob/master/src/popcount.rs) using the shuffle-based algorithm. For Jaccard distance, you are going to have to modify the code to AND and OR the vectors before applying `internal_popcount`, in the innermost loop.
